public enum TokenType {
    IDENTIFICADOR, NUMERO, STRING, EOF,
    SOMA, SUBTRACAO, MULTIPLICACAO, DIVISAO, MAIORIGUAL, MENORIGUAL, IGUALDADE, ATRIBUICAO, NEGACAO, DIFERENTE , MENOR, MAIOR, AND, OR,
    VIRGULA, PONTOVIRGULA, ABREPAR, FECHAPAR, ABRECHAVE, FECHACHAVE,
    IF, ELSE, WHILE, FOR, RETURN, PRINT , TRUE, FALSE
}
